# permissions for end users to edit limitcis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limitci-editor-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - limitcis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - limitcis/status
  verbs:
  - get
