# permissions for end users to view limitcis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limitci-viewer-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - limitcis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - limitcis/status
  verbs:
  - get
