# permissions for end users to edit plays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: play-editor-role
  labels:
    rbac.w6d.io/aggregate-ci-operator-role: "true"
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - plays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - plays/status
  verbs:
  - get
