---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-editor-role
  labels:
    rbac.w6d.io/aggregate-ci-operator-role: "true"
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineresources
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineresources/status
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns/status
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines/status
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns/status
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - tasks/status
    verbs:
      - get
