apiVersion: ci.w6d.io/v1alpha1
kind: Play
metadata:
  name: play-1-1
  namespace: p6e-cx-1
spec:
  name: nodejs-sample
  environment: develop
  scope:
    name: default
  stack:
    language: js
    package: npm
  project_id: 1
  pipeline_id: 1
  repo_url: https://github.com/w6d-io/nodejs-sample.git
  docker_url: w6dio/nodejs-sample:3010508c-main
  commit:
    sha: 3010508ce47519b9b7444dcd2d2961796c874cff
    ref: main
  domain: nodejs-sample.example.ci
  expose: true
  tasks:
    - unit-tests:
        image: node:latest
        script:
          - echo "unit-test1"
          - echo "unit-test2"
          - echo "unit-test3"
    - build:
        docker:
          filepath: Dockerfile
          context: .
        variables:
          BUILDENV: build
    - deploy:
        variables:
          BUILDENV: build
  dependencies:
    mongodb:
      variables:
        HOST: "$DB_HOST"
        PASSWORD: "$DB_PASSWORD"
        USERNAME: "$DB_USERNAME"
  secret:
    git_token: abcdef1234567890abcdef1234567890abcdef
    .dockerconfigjson: '{"auths":{"https://index.docker.io/v1/":{"auth":"personaldockertoken"}}}'
