---
domain: "example.ci"
ingress:
  class: nginx
workspaces:
  - name: values
    description: "Values file place holder"
    mountPath: /helm/values
  - name: config
    description: "Helm config folder"
    mountPath: /root/.config/helm
  - name: artifacts
    description: "Values artifacts place holder"
    mountPath: /artifacts
  - name: source
    description: "Values artifacts place holder"
    mountPath: /source
Volume:
  mode: "ReadWriteOnce"
  size: "2Gi"
serviceAccountName: bot-cx