---
domain: "example.ci"
ingress:
  class: nginx
  issuer: letsencrypt-prod
workspaces:
  - name: values
    description: "Values file place holder"
    mountPath: /helm/values
  - name: config
    description: "Helm config folder"
    mountPath: /root/.config/helm
  - name: artifacts
    description: "Values artifacts place holder"
    mountPath: /artifacts
  - name: source
    description: "Values source place holder"
    mountPath: /source
Volume:
  name: ws
  volumeClaimTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
cluster_role: bot-cx-role
hash:
  salt: wildcard
  min_length: 16
minio:
  host: mino.svc:9000
  access_key: ACCESSKEYSAMPLE
  secret_key: secretkeysample
  bucket: values
vault:
  host: vault.svc:8200
